name: WB Header
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: python3 inject.py
      - run: |
          git config user.name "bot"
          git config user.email "bot@x.com"
          git add *.html
          git diff --staged --quiet || git commit -m "header"
          git push
